In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1.0, 2.0], name="a")
b = tf.constant([2.0, 3.0], name="b")

In [3]:
result = a + b

In [4]:
result

<tf.Tensor 'add:0' shape=(2,) dtype=float32>

In [5]:
sess = tf.Session()
sess.run(result)

array([3., 5.], dtype=float32)

In [6]:
print(a.graph is tf.get_default_graph())

True


In [7]:
print(a.graph)

In [8]:
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v", shape=[1], initializer=tf.zeros_initializer)

In [9]:
g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable("v", shape=[1], initializer=tf.ones_initializer)

In [10]:
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

[0.]


In [11]:
with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

[1.]


In [12]:
print(2+6)

8


In [13]:
# tf.constant是一个计算，这个计算的结果为一个张量，保存在变量a中
a = tf.constant([1.0, 2.0], name="a")
b = tf.constant([2.0, 3.0], name="b")
result = tf.add(a, b, name="add")
print(result)

Tensor("add_1:0", shape=(2,), dtype=float32)


In [14]:
sess = tf.Session()
with sess.as_default():
    print(result.eval())

[3. 5.]


In [15]:
result

<tf.Tensor 'add_1:0' shape=(2,) dtype=float32>

In [16]:
print(sess.run(result))

[3. 5.]


In [17]:
print(result.eval(session=sess))

[3. 5.]


In [18]:
sess = tf.InteractiveSession()
print(result.eval())
sess.close()

[3. 5.]


In [19]:
config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)
sess1 = tf.InteractiveSession(config=config)
sess2 = tf.Session(config=config)

In [20]:
weights = tf.Variable(tf.random_normal([2, 3], stddev=2))

In [21]:
weights

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>

In [22]:
biases = tf.Variable(tf.zeros([3]))

In [23]:
biases

<tf.Variable 'Variable_1:0' shape=(3,) dtype=float32_ref>

In [26]:
w2 = tf.Variable(weights.initialized_value())
w3 = tf.Variable(weights.initialized_value() * 2.0)

In [27]:
import tensorflow as tf

# 声明w1、w2两个变量。这里还通过seed参数设定了随机种子。
# 这样可以保证每次运行得到的结果是一样的。
w1 = tf.Variable(tf.random_normal((2, 3), stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal((3, 1), stddev=1, seed=1))

# 暂时将输入的特征向量定义为一个常量。注意这里x是一个1x2的矩阵。
x = tf.constant([[0.7, 0.9]])

# 通过前向传播算法获得神经网络的输出。
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

sess = tf.Session()
# 这里不能直接通过sess.run(y)来获取y的取值。
# 因为w1和w2都还没有运行初始化过程。一下两行分别初始化了w1和w2两个变量。
sess.run(w1.initializer)  # 初始化w1
sess.run(w2.initializer)  # 初始化w2
# 输出
print(sess.run(y))
sess.close()

[[3.957578]]


In [34]:
w1 = tf.Variable(tf.random_normal([2, 3], stddev=1), name='w1')
print(w1)
w2 = tf.Variable(tf.random_normal([2, 3], dtype=tf.float32, stddev=1), name='w2')
w1.assign(w2)
print(w1)

<tf.Variable 'w1_5:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'w1_5:0' shape=(2, 3) dtype=float32_ref>


In [37]:
w1 = tf.Variable(tf.random_normal([2, 3], stddev=1), name='w1')
w2 = tf.Variable(tf.random_normal([2, 2], stddev=1), name='w2')
# 下面这句会报维度不匹配 的错误
# tf.assign(w1, w2)
# 这一句可以被成功执行
tf.assign(w1, w2, validate_shape=False)

<tf.Tensor 'Assign_8:0' shape=(2, 2) dtype=float32_ref>

In [40]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))

#定义placeholder作为存放输入数据的地方。这里的维度也不应要定义。
#但如果维度是确定的，那么给出维度可以降低出错的概率。
x = tf.placeholder(tf.float32, shape=(1, 2), name="input")
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

sess = tf.Session()
init_op = tf.global_variables_initializer()
sess.run(init_op)

# 下面一行将报错
# print(sess.run(y))

# 这一行不会报错
print(sess.run(y,feed_dict={x: [[0.7, 0.9]]}))

[[3.957578]]


In [1]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))

#定义placeholder作为存放输入数据的地方。这里的维度也不应要定义。
#但如果维度是确定的，那么给出维度可以降低出错的概率。
x = tf.placeholder(tf.float32, shape=(3, 2), name="input")
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

sess = tf.Session()
init_op = tf.global_variables_initializer()
sess.run(init_op)

# 下面一行将报错
# print(sess.run(y))

# 这一行不会报错
print(sess.run(y,feed_dict={x: [[0.7, 0.9], [0.1, 0.4], [0.5, 0.8]]}))

[[3.957578 ]
 [1.1537654]
 [3.1674924]]


In [4]:
%who

a	 init_op	 json	 sess	 tf	 w1	 w2	 x	 y	 
yapf_reformat	 


In [3]:
import tensorflow as tf

# 通过numpy生成模拟数据集
from numpy.random import RandomState

# 定义训练数据batch的大小
batch_size = 8

# 定义神经网络的参数，这里还是沿用3.4.2小节中给出的神经网络结构。
w1 = tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))

# 在shape的一个维度上使用None 可以方便使用不同的batch大小。在训练时，需要把数据分
# 成比较小的batch，但是在测试时，可以一次性使用全部的数据。当数据集比较小时这样比
# 较方便测试，但数据集比较大时，将大量数据放入一个batch可能会导致内存溢出。
x = tf.placeholder(tf.float32, shape=(None, 2), name='x-input')
y_ = tf.placeholder(tf.float32, shape=(None, 1), name='y-input')

# 定义神经网络前向传播的过程
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

# 定义损失函数和反向传播的算法。
y = tf.sigmoid(y)
cross_entropy = -tf.reduce_mean(
    y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)) 
    + (1-y_) * tf.log(tf.clip_by_value(1-y, 1e-10, 1.0))
)
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

# 通过随机数生成一个模拟数据集。
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size, 2)
# 定义规则来给出样本的标签。在这里所有x1 + x2 < 1 的样例都被认为是正样本
# （比如零件合格），而其他为负样本（比如零件不合格）。和TensorFlow游乐场中的
# 表示法不大一样的地方是，在这里使用0来表示负样本，1来表示正样本。大部分解决
# 分类问题的神经网络都会采用0和1的表示方法。
Y = [[int(x1+x2<1)] for (x1, x2) in X]

# 创建一个会话来运行Tensorflow程序。
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    # 初始化变量。
    sess.run(init_op)
    
    print(sess.run(w1))
    print(sess.run(w2))
    
    # 设置训练的轮数
    STEPS = 8000
    for i in range(STEPS):
        # 每次选取batch_size个样本进行训练。
        start = (i * batch_size) % dataset_size
        end = min(start+batch_size, dataset_size)
        
        # 通过选取的样本训练神经网络并更新参数。
        sess.run(train_step, feed_dict={x: X[start: end], y_: Y[start: end]})
        if i % 1000 == 0:
            # 每隔一段时间计算在所有数据上的交叉熵并输出。
            total_cross_entropy = sess.run(
                cross_entropy, feed_dict={x: X, y_: Y}
            )
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))
            
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
After 0 training step(s), cross entropy on all data is 1.89805
After 1000 training step(s), cross entropy on all data is 0.655075
After 2000 training step(s), cross entropy on all data is 0.626172
After 3000 training step(s), cross entropy on all data is 0.615096
After 4000 training step(s), cross entropy on all data is 0.610309
After 5000 training step(s), cross entropy on all data is 0.608679
After 6000 training step(s), cross entropy on all data is 0.608231
After 7000 training step(s), cross entropy on all data is 0.608114
[[ 0.08208176  0.5239096   1.7477902 ]
 [-2.2339835  -0.20824055  1.0780488 ]]
[[-0.4916839]
 [ 0.4147874]
 [-1.003934 ]]


In [3]:
import tensorflow as tf

In [4]:
v = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [5]:
sess = tf.Session()
print(tf.clip_by_value(v, 2.5, 4.5).eval(session = sess))

[[2.5 2.5 3. ]
 [4.  4.5 4.5]]


In [8]:
v2 = tf.constant([1.0, 2.0, 3.0])

In [10]:
print(tf.log(v2).eval(session=sess))

[0.        0.6931472 1.0986123]


In [7]:
v = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [9]:
print(tf.reduce_mean(v).eval(session=sess))

3.5


In [12]:
import tensorflow as tf
v1 = tf.constant([1.0, 2.0, 3.0, 4.0])
v2 = tf.constant([4.0, 3.0, 2.0, 1.0])

sess = tf.InteractiveSession()
print(tf.greater(v1, v2).eval())

print(tf.where(tf.greater(v1, v2), v1, v2).eval())
sess.close()

[False False  True  True]
[4. 3. 3. 4.]


In [16]:
import tensorflow as tf
from numpy.random import RandomState

batch_size = 8

# 两个输入节点
x = tf.placeholder(tf.float32, shape=(None, 2), name='x_input')
# 回归问题一般只有一个输出节点
y_ = tf.placeholder(tf.float32, shape=(None, 1), name='y_input')

# 定义了一个单层的神经网络前向传播的过程，这里就是简单加权和。
w1 = tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

# 定义预测多了和预测少了的成本
loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

# 通过随机数生成一个模拟数据
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size, 2)

# 设置回归的正确值为两个输入的和加上一个随机量。之所以要加上一个随机量是为了
# 加入不可预测的噪音，否则不同损失函数的意义就不大了，因为不同损失函数都会在能
# 完全预测正确的时候最低。一般来说噪音为一个均值为0的小量，所以这里的噪音设置为
# -0.05 ~ 0.05 的随机数。

Y = [[x1 + x2 + rdm.rand()/10.0 - 0.05] for (x1, x2) in X]

# 训练神经网络
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i * batch_size) % dataset_size
        end = min(start + batch_size, dataset_size)
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
    print(sess.run(w1))

[[1.019347 ]
 [1.0428089]]


In [17]:
weights = tf.constant([[1.0, -2.0], [-3.0, 4.0]])
with tf.Session() as sess:
    # 输出为l1正则化，其中0.5为正则化项的权重。
    print(sess.run(tf.contrib.layers.l1_regularizer(0.5)(weights)))
    # 输出为l2正则化
    print(sess.run(tf.contrib.layers.l2_regularizer(0.5)(weights)))

5.0
7.5


In [ ]:
import tensorflow as tf

# 获取一层神经网络边上的权重，并将这个权重的L2正则化损失加入名称为'losses'的集合中
def get_weight(shape, lambda1):
    # 生成一个变量。
    var = tf.Variable(tf.random_normal(shape), dtype=tf.float32)
    
    # add_to_collection函数将这个新生变量的L2正则化损失项加入集合
    # 这个函数的第一个参数'losses'是集合的名字，第二个参数是要加入这个集合的内容。
    tf.add_to_collection(
        'losses', tf.contrib.layers.l2_regularizer(lambda1)(var)
    )
    # 返回生成的变量
    return var


x = tf.placeholder(tf.float32, shape=(None. 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))
batch_size = 8
# 定义了每一层网络中节点的个数
layer_dimension = [2, 10, 10, 10, 1]
# 神经网络的层数
n_layers = len(layer_dimension)

# 这个变量维护前向传播时最深层的节点，开始的时候就是输入层。
cur_layer = x
# 当前层的节点个数
in_dimension = layer_dimension[0]

# 通过一个循环来生成5层全连接的神经网络结构
for i in range(1, n_layers):
    # layer_dimension[i]为下一层的节点个数。
    out_dimension = layer_dimension[i]
    # 生成当前层中权重的变量，并将这个变量的L2正则化损失加入计算图上的集合
    weight = get_weight([in_dimension, out_dimension], 0.001)
    bias = tf.Variable(tf.constant(0.1, shape=[out_dimension]))
    # 使用ReLU激活函数
    cur_layer = tf.nn.relu(tf.matmul(cur_layer, weight) + bias)
    # 进入下一层之前将下一层的节点个数更新为当前层节点个数
    in_dimension = layer_dimension[i]

# 在定义神经网络前向传播的同时已经将所有的L2正则化损失加入了图上的集合
# 这里只需要计算刻画模型在训练数据上表现的损失函数
mse_loss = tf.reduce_mean(tf.square(y_ - cur_layer))

# 将均方误差损失函数加入损失集合
tf.add_to_collection('losses', mse_loss)

# get_collection返回一个列表，这个列表是所有这个集合中的元素。在这个样例中，
# 这些元素就是损失函数的不同部分，将它们加起来就可以得到最终的损失函数。
loss = tf.add_n(tf.get_collection('losses'))

In [19]:
import tensorflow as tf

# 定义一个变量用于计算滑动平均，这个变量的初始值为0.注意这里手动制定了变量的
# 类型为tf.float32，因为所有需要计算滑动平均的变量必须是实数形。
v1 = tf.Variable(0, dtype=tf.float32)
# 这里step变量模拟神经网络中迭代的轮数，可以用于动态控制衰减率
step = tf.Variable(0, trainable=False)

# 定义一个滑动平均的类（class）。初始化时给定了衰减率（0.99）和控制衰减率的变量step
ema = tf.train.ExponentialMovingAverage(0.99, step)

# 定义一个更新变量滑动平均的操作。这里需要给定一个列表，每次执行这个操作时
# 这个列表中的变量都会被更新。
maintain_averages_op = ema.apply([v1])

with tf.Session() as sess:
    # 初始化所有的变量
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    # 通过ema.average(v1)获取滑动平均之后变量的取值。在初始化之后变量v1的值
    # 和v1的滑动平均都为0
    print(sess.run([v1, ema.average(v1)]))
    
    # 更新变量v1的值到5
    sess.run(tf.assign(v1, 5))
    # 更新v1的滑动平均值。衰减率为min{0.99, (1+step)/(10+step) = 0.1 }=1
    # 所以v1的滑动平均会被更新为0.1*0+0.9*5=4.5
    sess.run(maintain_averages_op)
    print(sess.run([v1, ema.average(v1)]))
    
    # 鞥更新step的值为100000.
    sess.run(tf.assign(step, 100000))
    # 更新v1的值为10
    sess.run(tf.assign(v1, 10))
    # 更新v1的滑动平均值。衰减率为min({0.99, (1+step)/(10+step=0.999}=0.99
    # 所以v1的滑动平均会被更新为0.99*4.5+0.01*10=4.555
    sess.run(maintain_averages_op)
    print(sess.run([v1, ema.average(v1)]))
    

[0.0, 0.0]
[5.0, 4.5]
[10.0, 4.555]
