In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

iris = load_iris()
X = iris.data[:, (2, 3)]
y = (iris.target == 0).astype(np.int)
per_clf = Perceptron(random_state=42)
per_clf.fit(X, y)

y_pred = per_clf.predict([[2, 0.5]])
print(y_pred)

In [1]:
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/")

W0904 14:30:42.757139  9440 deprecation.py:323] From <ipython-input-1-761bd243aaf1>:3: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0904 14:30:42.763154  9440 deprecation.py:323] From d:\python3.5.3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
W0904 14:30:42.763696  9440 deprecation.py:323] From d:\python3.5.3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to impl

Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/train-images-idx3-ubyte.gz


W0904 14:30:42.957180  9440 deprecation.py:323] From d:\python3.5.3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
W0904 14:30:42.994082  9440 deprecation.py:323] From d:\python3.5.3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/train-labels-idx1-ubyte.gz
Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/t10k-labels-idx1-ubyte.gz


In [2]:
X_train = mnist.train.images
X_test = mnist.test.images
y_train = mnist.train.labels.astype("int")
y_test = mnist.test.labels.astype("int")

In [3]:
import tensorflow as tf

config = tf.contrib.learn.RunConfig(tf_random_seed=42) # not shown in the config

feature_cols = tf.contrib.learn.infer_real_valued_columns_from_input(X_train)
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[300,100], n_classes=10,
                                         feature_columns=feature_cols, config=config)
dnn_clf = tf.contrib.learn.SKCompat(dnn_clf) # if TensorFlow >= 1.1
dnn_clf.fit(X_train, y_train, batch_size=50, steps=40000)

W0904 14:30:48.662095  9440 deprecation.py:323] From <ipython-input-3-4a831b14704e>:3: RunConfig.__init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
W0904 14:30:48.679064  9440 deprecation.py:323] From <ipython-input-3-4a831b14704e>:5: infer_real_valued_columns_from_input (from tensorflow.contrib.learn.python.learn.estimators.estimator) is deprecated and will be removed in a future version.
Instructions for updating:
Please specify feature columns explicitly.
W0904 14:30:48.679064  9440 deprecation.py:323] From d:\python3.5.3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py:143: setup_train_data_feeder (from tensorflow.contrib.learn.python.learn.learn_io.data_feeder) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tensorflow/trans

SKCompat()

In [4]:
from sklearn.metrics import accuracy_score

y_pred = dnn_clf.predict(X_test)
accuracy_score(y_test, y_pred['classes'])

W0904 14:32:36.191894  9440 deprecation.py:323] From d:\python3.5.3\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


0.9816

In [7]:
y_pred['probabilities'][0]

array([1.17556659e-10, 7.24984254e-13, 4.50217197e-10, 1.10052520e-06,
       3.86898350e-15, 1.36183355e-13, 7.31454567e-19, 9.99998808e-01,
       1.11068196e-10, 1.72052296e-07], dtype=float32)

In [8]:
y_pred['classes'][0]

7

In [9]:
from sklearn.metrics import log_loss

y_pred_proba = y_pred['probabilities']
log_loss(y_test, y_pred_proba)

0.07208803419083464

- 库还包含了一些方便的函数来评估模型：

In [11]:
dnn_clf.score(X_test, y_test)

{'accuracy': 0.9816, 'global_step': 40000, 'loss': 0.071289584}

In [16]:
import tensorflow as tf
import numpy as np

In [13]:
n_inputs = 28*28
n_hidden1 = 300
n_hidden2 = 100
n_outputs = 10

In [15]:
X = tf.placeholder(tf.float32, shape=(None, n_inputs), name="X")
y = tf.placeholder(tf.int64, shape=(None), name="y")

In [17]:
def neuron_layer(X, n_neurons, name, activation=None):
    with tf.name_scope(name):
        n_inputs = int(X.get_shape()[1])
        stddev = 2 / np.sqrt(n_inputs)
        init = tf.truncated_normal((n_inputs, n_neurons), stddev=stddev)
        W = tf.Variable(init, name="weights")
        b = tf.Variable(tf.zeros([n_neurons]), name="biases")
        z = tf.matmul(X, W) + b
        if activation == "relu":
            return tf.nn.relu(z)
        else:
            return z

In [18]:
with tf.name_scope("dnn"):
    hidden1 = neuron_layer(X, n_hidden1, "hidden1", activation="relu")
    hidden2 = neuron_layer(hidden1, n_hidden2, "hidden2", activation="relu")
    logits = neuron_layer(hidden2, n_outputs, "outputs")

- 利用fully_connected()函数来替换自己写的neuron_layer()函数

In [21]:
from tensorflow.contrib.layers import fully_connected

In [33]:
with tf.name_scope("dnn"):
    hidden1 = fully_connected(X, n_hidden1, scope="hidden_1")
    hidden2 = fully_connected(hidden1, n_hidden2, scope="hidden_2")
    logits2 = fully_connected(hidden2, n_outputs, scope="outputs_", activation_fn=None)

In [28]:
with tf.name_scope("loss"):
    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits2)
    loss = tf.reduce_mean(xentropy, name="loss")

In [29]:
learning_rate = 0.01
with tf.name_scope("train"):
    optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    training_op = optimizer.minimize(loss)

In [30]:
with tf.name_scope("eval"):
    correct = tf.nn.in_top_k(logits2, y, 1)
    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

In [31]:
init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [34]:
from tensorflow.examples.tutorials.mnist import input_data

In [35]:
mnist = input_data.read_data_sets("D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/")

Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/train-images-idx3-ubyte.gz
Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/train-labels-idx1-ubyte.gz
Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting D:/李添的数据哦！！！/BookStudy/book4/MNIST_data/MNIST_data/t10k-labels-idx1-ubyte.gz


In [36]:
n_epochs = 400
batch_size = 50

In [38]:
with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for iteration in range(mnist.train.num_examples // batch_size):
            X_batch, y_batch = mnist.train.next_batch(batch_size)
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        acc_train = accuracy.eval(feed_dict={X: X_batch, y: y_batch})
        acc_test = accuracy.eval(feed_dict={X: mnist.test.images, y: mnist.test.labels})
        print(epoch, "Train accuracy：", acc_train, "Test accuracy：", acc_test)
    save_path = saver.save(sess, "D:/李添的数据哦！！！/BookStudy/book4/model/my_model_final.ckpt")

0 Train accuracy： 0.92 Test accuracy： 0.8993
1 Train accuracy： 0.86 Test accuracy： 0.9194
2 Train accuracy： 0.94 Test accuracy： 0.9284
3 Train accuracy： 0.96 Test accuracy： 0.9347
4 Train accuracy： 0.94 Test accuracy： 0.9409
5 Train accuracy： 0.94 Test accuracy： 0.9455
6 Train accuracy： 0.96 Test accuracy： 0.9494
7 Train accuracy： 0.88 Test accuracy： 0.9528
8 Train accuracy： 0.98 Test accuracy： 0.9534
9 Train accuracy： 0.98 Test accuracy： 0.9566
10 Train accuracy： 0.92 Test accuracy： 0.9584
11 Train accuracy： 1.0 Test accuracy： 0.9603
12 Train accuracy： 0.92 Test accuracy： 0.9617
13 Train accuracy： 0.96 Test accuracy： 0.9638
14 Train accuracy： 0.98 Test accuracy： 0.9643
15 Train accuracy： 1.0 Test accuracy： 0.9653
16 Train accuracy： 0.96 Test accuracy： 0.9675
17 Train accuracy： 0.94 Test accuracy： 0.9678
18 Train accuracy： 0.9 Test accuracy： 0.9688
19 Train accuracy： 0.98 Test accuracy： 0.9702
20 Train accuracy： 0.98 Test accuracy： 0.9703
21 Train accuracy： 1.0 Test accuracy： 0.9713
22

In [41]:
X_test[0].reshape(1, -1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [42]:
with tf.Session() as sess:
    saver.restore(sess, "D:/李添的数据哦！！！/BookStudy/book4/model/my_model_final.ckpt")
    X_new_scaled = X_test[0].reshape(1, -1)
    Z = logits.eval(feed_dict={X: X_new_scaled})
    y_pred = np.argmax(Z, axis=1)

In [43]:
y_pred

array([6], dtype=int64)

In [44]:
Z

array([[1.0172969 , 3.8071704 , 0.494485  , 2.3816898 , 1.7650498 ,
        0.6520101 , 4.10833   , 0.        , 0.        , 0.60733944]],
      dtype=float32)