In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3,4)

In [7]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
X.numel()

12

In [9]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
x.reshape(-1, 3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [11]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.randn(3,4)

tensor([[ 2.2934,  0.4651, -0.2350, -0.3736],
        [ 0.1281,  0.0650, -0.1469,  2.6429],
        [-0.8253, -0.4808, -0.1956, -0.5463]])

In [13]:
x = torch.tensor([1.0, 2, 4, 8])

In [14]:
x

tensor([1., 2., 4., 8.])

In [15]:
y = torch.tensor([2, 2, 2, 2])

In [16]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [17]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [18]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [19]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [20]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [21]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [22]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))

In [23]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [25]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [26]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [27]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [28]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
X.sum()

tensor(66.)

In [30]:
a = torch.arange(3).reshape((3, 1))

In [31]:
b = torch.arange(2).reshape((1, 2))

In [32]:
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [33]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [35]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [36]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [38]:
X[1, 2]=9

In [39]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
X[0:2, :] = 9

In [41]:
X

tensor([[ 9.,  9.,  9.,  9.],
        [ 9.,  9.,  9.,  9.],
        [ 8.,  9., 10., 11.]])

In [42]:
before = id(Y)

In [43]:
before

2221968775032

In [44]:
Y = Y + X

In [45]:
id(Y)

2221968807480

In [46]:
Z = torch.zeros_like(Y)

In [47]:
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
id(Z)

2221968782744

In [49]:
Z[:] = X + Y

In [50]:
id(Z)

2221968782744

In [51]:
Z

tensor([[20., 19., 22., 21.],
        [19., 20., 21., 22.],
        [20., 21., 22., 23.]])

In [53]:
Y[:] = X + Y

In [54]:
id(Y)

2221968807480

In [55]:
A = X.numpy()

In [56]:
A

array([[ 9.,  9.,  9.,  9.],
       [ 9.,  9.,  9.,  9.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [57]:
B = torch.tensor(A)

In [58]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [59]:
a = torch.tensor([3.5])

In [60]:
a

tensor([3.5000])

In [61]:
a

tensor([3.5000])

In [ ]:
a.item()

## 数据预处理

1. 读取数据集

In [1]:
import os

In [3]:
os.makedirs('data', exist_ok=True)

In [4]:
data_file = 'data/house_tiny.csv'

In [5]:
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [6]:
import pandas as pd

In [7]:
data = pd.read_csv(data_file)

In [8]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

2. 处理缺失值

In [10]:
inputs, outputs = data.iloc[:, 0: 2], data.iloc[:, 2]

In [11]:
inputs = inputs.fillna(inputs.mean())

D:\python3.78\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


In [12]:
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [13]:
inputs = pd.get_dummies(inputs, dummy_na=True)

In [14]:
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

3. 转换为张量格式

In [15]:
import torch

In [16]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)

In [17]:
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [18]:
x = torch.tensor(3.0)

In [19]:
x

tensor(3.)

In [20]:
x + x

tensor(6.)

In [22]:
A = torch.arange(20).reshape(5, 4)

In [23]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [1]:
import torch

In [2]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])

In [3]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [4]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [5]:
X = torch.arange(24).reshape(2,3,4)

In [6]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [7]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [8]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [9]:
B = A.clone()

In [10]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [11]:
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [13]:
x = torch.arange(4, dtype=torch.float32)

In [14]:
x

tensor([0., 1., 2., 3.])

In [15]:
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [16]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [17]:
A.sum()

tensor(190.)

In [18]:
A.shape

torch.Size([5, 4])

In [19]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [20]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [21]:
A.sum(axis=1, keepdim=True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [23]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [24]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [25]:
x = torch.arange(4, dtype=torch.float32)

In [26]:
x

tensor([0., 1., 2., 3.])

In [27]:
y = torch.ones(4, dtype = torch.float32)

In [28]:
y

tensor([1., 1., 1., 1.])

In [29]:
torch.dot(x, y)

tensor(6.)