In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [8]:
X = x.reshape(3,4)

In [9]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
X.numel()

12

In [11]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
x.reshape(-1, 3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [14]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.randn(3,4)

tensor([[ 1.2315,  0.2947,  0.0617,  0.2486],
        [-0.7767,  0.6944, -0.5622,  0.8187],
        [ 1.3395, -2.9440,  1.0535,  0.9027]])

In [16]:
x = torch.tensor([1.0, 2, 4, 8])

In [17]:
x

tensor([1., 2., 4., 8.])

In [18]:
y = torch.tensor([2, 2, 2, 2])

In [19]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [20]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [22]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [23]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [24]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [25]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])