1

In [1]:
import numpy as np

In [5]:
x = np.zeros(10)
x[4] = 1

In [6]:
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2

In [8]:
x = np.arange(10, 50, 1)

In [9]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3

In [10]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4

In [11]:
x = np.random.random([10, 10])

In [13]:
x.max(), x.min()

(0.9988500977505944, 0.005402550802459216)

5

In [15]:
x = np.zeros((10, 10), dtype=np.int8)

In [17]:
x[[0, -1]] = 1

In [19]:
x[:, [0, -1]] = 1

In [20]:
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

6

In [29]:
np.array(np.arange(1, 6, 1).tolist()*5).reshape((5,5))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

7

In [30]:
np.linspace(0, 1, 12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8

In [32]:
x = np.random.random(10)
x.sort()

In [33]:
x

array([0.09954637, 0.23154675, 0.29650233, 0.3648797 , 0.56364311,
       0.62906698, 0.81264057, 0.84215773, 0.92915421, 0.99273399])

9

In [36]:
x = np.random.randint(1, 10, size=10)

In [37]:
x

array([6, 9, 3, 1, 6, 1, 4, 6, 3, 9])

In [38]:
v_max = x.max()
condition = x == v_max
x[condition] = -10

In [39]:
x

array([  6, -10,   3,   1,   6,   1,   4,   6,   3, -10])

9另一个解

In [40]:
v_min = x.min()
index = np.argwhere(x == v_min)
for i in index:
    x[i[0]] = 1024

In [41]:
x

array([   6, 1024,    3,    1,    6,    1,    4,    6,    3, 1024])

10

In [43]:
x = np.random.randint(0, 150, size=(5,5))

In [47]:
index = x[:, 2].argsort()

In [48]:
x[index]

array([[ 74,  89,  27,  42,  88],
       [ 54,  67,  65,   3,  82],
       [ 94, 122,  97, 118,  61],
       [ 88, 106, 107, 129, 108],
       [ 28,  31, 134, 104,  33]])

11

In [51]:
x = np.random.randint(0,10, size=(3,4,5,6))

In [56]:
y = x.sum(axis=-1).sum(axis=-1)

In [59]:
y

array([[116, 136, 104, 146],
       [143, 138, 139, 135],
       [107, 138, 149, 149]])

In [57]:
y.shape

(3, 4)

In [58]:
x.sum(axis=(-1,-2))

array([[116, 136, 104, 146],
       [143, 138, 139, 135],
       [107, 138, 149, 149]])

12

In [60]:
x = np.arange(1, 6)

In [62]:
y = np.zeros(17, dtype=np.int8)

In [64]:
y[::4] = x

In [65]:
y

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5], dtype=int8)

13

In [68]:
x = np.random.randint(1, 10, (3, 4))

In [69]:
x

array([[8, 7, 2, 9],
       [3, 7, 9, 9],
       [8, 2, 1, 6]])

In [71]:
x[[0, 2]] = x[[2, 0]]

In [72]:
x

array([[8, 2, 1, 6],
       [3, 7, 9, 9],
       [8, 7, 2, 9]])

14

In [1]:
import numpy as np
x = np.random.randn(100000)

In [2]:
%%time
np.power(x, 3)

Wall time: 5 ms


array([-6.55791837e-02, -1.53930626e-07, -8.08115043e-01, ...,
       -4.73709296e-01,  1.31192834e+01,  1.45918537e+00])

In [3]:
%%time
ret = []
for i in x:
    ret.append(i**3)

Wall time: 56 ms


15

In [4]:
a = np.random.randint(0, 10, size=(5,3))
b = np.random.randint(0, 10, size=(3, 2))

In [5]:
np.dot(a, b)

array([[107,  82],
       [103,  87],
       [131,  96],
       [ 68,  55],
       [133,  89]])

16

In [7]:
x = np.random.randint(0, 10, size=(4,5))

In [9]:
v_mean = x.mean(axis=1)

In [10]:
x - v_mean.reshape(4, 1)

array([[ 0.4,  2.4, -1.6, -3.6,  2.4],
       [ 2.2, -4.8,  1.2, -0.8,  2.2],
       [ 3.4,  4.4, -3.6, -1.6, -2.6],
       [ 3.4, -0.6, -5.6, -0.6,  3.4]])

17

In [11]:
x = np.zeros(shape=(8,8), dtype=np.int8)

In [14]:
x[::2, 1::2] = 1

In [16]:
x[1::2, ::2] = 1

In [17]:
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

18

In [18]:
x = np.random.randint(0, 100, size=(4,5))

In [21]:
v_min = x.min(axis=0)
v_max = x.max(axis=0)

In [22]:
(x - v_min) / (v_max - v_min)

array([[1.        , 1.        , 0.94594595, 0.05714286, 1.        ],
       [0.2       , 0.49382716, 1.        , 0.        , 0.36      ],
       [0.        , 0.        , 0.        , 0.65714286, 0.        ],
       [0.625     , 0.54320988, 0.7972973 , 1.        , 0.2       ]])

20

In [33]:
x = np.random.randint(0, 100, size=20)

In [35]:
for i in range(20):
    for j in range(i+1, 20):
        if x[i] > x[j]:
            x[i], x[j] = x[j], x[i]

In [36]:
x

array([ 3,  4,  7, 15, 16, 21, 40, 47, 57, 57, 75, 80, 83, 85, 89, 91, 93,
       93, 97, 99])