## Pandas基础

In [1]:
import pandas as pd

In [3]:
pd.__version__

'0.23.3'

In [4]:
import numpy as np

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [6]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
data[1]

0.5

In [10]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [12]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

In [13]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [14]:
data['b']

0.5

In [15]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])

In [16]:
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [17]:
data[5]

0.5

In [18]:
population_dict = {'a': 33, 'b': 58, 'c': 32, 'd': 99}

In [19]:
s = pd.Series(population_dict)

In [20]:
s

a    33
b    58
c    32
d    99
dtype: int64

In [21]:
s[0]

33

In [22]:
s['a':'b']

a    33
b    58
dtype: int64

In [23]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [24]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [25]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [26]:
population_dict

{'a': 33, 'b': 58, 'c': 32, 'd': 99}

In [28]:
name_dict = {'a': 'A', 'b': 'B', 'c': 'C', 'd': 'D'}

In [30]:
name_dict

{'a': 'A', 'b': 'B', 'c': 'C', 'd': 'D'}

In [31]:
name = pd.Series(name_dict)

In [32]:
name

a    A
b    B
c    C
d    D
dtype: object

In [34]:
states =  pd.DataFrame({'population': s, 'name': name})

In [36]:
states

name  population
a    A          33
b    B          58
c    C          32
d    D          99

In [37]:
states.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [38]:
states.columns

Index(['name', 'population'], dtype='object')

In [43]:
states['population']

a    33
b    58
c    32
d    99
Name: population, dtype: int64

In [44]:
s

a    33
b    58
c    32
d    99
dtype: int64

In [45]:
pd.DataFrame(s, columns=['population'])

population
a          33
b          58
c          32
d          99

In [46]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]

In [47]:
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [48]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [49]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [50]:
population_dict

{'a': 33, 'b': 58, 'c': 32, 'd': 99}

In [51]:
s

a    33
b    58
c    32
d    99
dtype: int64

In [52]:
np.random.rand(3, 2)

array([[0.08341741, 0.35273894],
       [0.01318488, 0.98664951],
       [0.18950095, 0.08509624]])

In [53]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.031852  0.698977
b  0.818500  0.525783
c  0.196517  0.385278

In [54]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])

In [55]:
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [56]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [57]:
ind = pd.Index([2, 3, 5, 7, 11])

In [58]:
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [59]:
ind[1]

3

In [60]:
ind[:2]

Int64Index([2, 3], dtype='int64')

In [61]:
ind.size, ind.shape, ind.ndim, ind.dtype

(5, (5,), 1, dtype('int64'))

In [62]:
ind[1] = 0

TypeError: Index does not support mutable operations

In [63]:
indA = pd.Index([1, 3, 5, 7, 9])

In [64]:
indB = pd.Index([2, 3, 5, 7, 11])

In [65]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [66]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

异或，两个set中不同的值的集合

In [67]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [68]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

## 数据取值与选择

In [2]:
import pandas as pd

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1], index=['a', 'b', 'c', 'd'])

In [4]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data['b']

0.5

In [6]:
'a' in data

True

In [7]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [9]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['e'] = 1.25

In [11]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

将显式索引作为切片

In [14]:
data['a': 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

将隐式整数索引作为切片

In [15]:
data[0: 2]

a    0.25
b    0.50
dtype: float64

掩码

In [16]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

花哨的索引

In [17]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [18]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

In [19]:
data

1    a
3    b
5    c
dtype: object

取值操作是显式索引

In [20]:
data[1]

'a'

切片操作是隐式索引

In [21]:
data[1:3]

3    b
5    c
dtype: object

索引器

In [22]:
data.loc[1]

'a'

In [23]:
data.loc[1: 3]

1    a
3    b
dtype: object

In [24]:
data.iloc[1]

'b'

In [25]:
data.iloc[1:3]

3    b
5    c
dtype: object

### DataFrame数据选择方法

将DataFrame看作字典

In [26]:
area = pd.Series({'aa': 423967, 
                 'bb': 695662, 
                 'cc': 141297, 
                 'dd': 170312, 
                 'ee': 149995})

In [27]:
pop = pd.Series({'aa': 38332521, 
                'bb': 26448193, 
                'cc': 19651127, 
                'dd': 19552860, 
                'ee': 12882135})

In [28]:
data = pd.DataFrame({'area': area, 'pop': pop})

In [29]:
data

area       pop
aa  423967  38332521
bb  695662  26448193
cc  141297  19651127
dd  170312  19552860
ee  149995  12882135

In [30]:
data['area']

aa    423967
bb    695662
cc    141297
dd    170312
ee    149995
Name: area, dtype: int64

In [31]:
data.area

aa    423967
bb    695662
cc    141297
dd    170312
ee    149995
Name: area, dtype: int64

In [32]:
data.area is data['area']

True

In [33]:
data.pop

<bound method NDFrame.pop of       area       pop
aa  423967  38332521
bb  695662  26448193
cc  141297  19651127
dd  170312  19552860
ee  149995  12882135>

In [34]:
data['pop']

aa    38332521
bb    26448193
cc    19651127
dd    19552860
ee    12882135
Name: pop, dtype: int64

In [35]:
data['density'] = data['pop'] / data['area']

In [36]:
data

area       pop     density
aa  423967  38332521   90.413926
bb  695662  26448193   38.018740
cc  141297  19651127  139.076746
dd  170312  19552860  114.806121
ee  149995  12882135   85.883763

将DataFrame看作二维数组

In [37]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [38]:
data

area       pop     density
aa  423967  38332521   90.413926
bb  695662  26448193   38.018740
cc  141297  19651127  139.076746
dd  170312  19552860  114.806121
ee  149995  12882135   85.883763

In [39]:
data.T

aa            bb            cc            dd            ee
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [40]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [41]:
data.values[:, 0]

array([423967., 695662., 141297., 170312., 149995.])

In [42]:
data['area']

aa    423967
bb    695662
cc    141297
dd    170312
ee    149995
Name: area, dtype: int64

In [43]:
data.iloc[:3, :2]

area       pop
aa  423967  38332521
bb  695662  26448193
cc  141297  19651127

In [44]:
data.loc[:'cc', :'pop']

area       pop
aa  423967  38332521
bb  695662  26448193
cc  141297  19651127

In [45]:
data.ix[:3, :'pop']

/Users/momo/.pyenv/versions/3.5.4/lib/python3.5/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
aa  423967  38332521
bb  695662  26448193
cc  141297  19651127

In [46]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
cc  19651127  139.076746
dd  19552860  114.806121

In [47]:
data.iloc[0, 2] = 90

In [48]:
data

area       pop     density
aa  423967  38332521   90.000000
bb  695662  26448193   38.018740
cc  141297  19651127  139.076746
dd  170312  19552860  114.806121
ee  149995  12882135   85.883763

其他取值方法

In [49]:
data['bb': 'cc']

area       pop     density
bb  695662  26448193   38.018740
cc  141297  19651127  139.076746

In [50]:
data[1:3]

area       pop     density
bb  695662  26448193   38.018740
cc  141297  19651127  139.076746

In [51]:
data[data.density > 100]

area       pop     density
cc  141297  19651127  139.076746
dd  170312  19552860  114.806121

## Pandas数值运算方法

In [52]:
import pandas as pd
import numpy as np

In [53]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))

In [54]:
ser

0    6
1    3
2    7
3    4
dtype: int64

In [55]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])

In [56]:
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [57]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [58]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [60]:
area = pd.Series({'aa': 423967, 
                 'bb': 695662, 
                 'cc': 141297, 
                 'dd': 170312, 
                 'ee': 149995}, name='area')

In [61]:
pop = pd.Series({'aa': 38332521, 
                'bb': 26448193, 
                'cc': 19651127, 
                'dd': 19552860, 
                'ee': 12882135}, name='population')

In [63]:
pop / area

aa     90.413926
bb     38.018740
cc    139.076746
dd    114.806121
ee     85.883763
dtype: float64

In [64]:
area.index

Index(['aa', 'bb', 'cc', 'dd', 'ee'], dtype='object')

In [65]:
pop.index

Index(['aa', 'bb', 'cc', 'dd', 'ee'], dtype='object')

In [66]:
area.index | pop.index

Index(['aa', 'bb', 'cc', 'dd', 'ee'], dtype='object')

In [67]:
a = pd.Series([2, 4, 6], index=[0, 1, 2])

In [68]:
b = pd.Series([1, 3, 5], index=[1, 2, 3])

In [69]:
a + b

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [70]:
a.add(b, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [71]:
a = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))

In [72]:
a

A   B
0  1  11
1  5   1

In [73]:
b = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))

In [74]:
b

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [75]:
a + b

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [78]:
fill = a.stack().mean()

In [79]:
fill

4.5

In [80]:
a.add(b, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [81]:
a

A   B
0  1  11
1  5   1

In [82]:
a = rng.randint(10, size=(3, 4))

In [83]:
a

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [84]:
a - a[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [85]:
df = pd.DataFrame(a, columns=list('QRST'))

In [86]:
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [87]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [88]:
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [89]:
df.sub(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [90]:
halfrow = df.iloc[0, ::2]

In [91]:
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [92]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

## 处理缺失值

None: Python对象类型的缺失值

In [93]:
import numpy as np
import pandas as pd

In [94]:
vals1 = np.array([1, None, 3, 4])

In [95]:
vals1

array([1, None, 3, 4], dtype=object)

In [96]:
for dtype in ['object', 'int']:
    print("dtype = ", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype =  object
73.2 ms ± 834 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype =  int
2.31 ms ± 191 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [97]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

NaN: 数值类型的缺失值

In [98]:
vals2 = np.array([1, np.nan, 3, 4])

In [99]:
vals2

array([ 1., nan,  3.,  4.])

In [101]:
vals2.dtype

dtype('float64')

In [102]:
1 + np.nan

nan

In [103]:
0 * np.nan

nan

In [104]:
vals2.sum()

nan

In [105]:
vals2.min()

/Users/momo/.pyenv/versions/3.5.4/lib/python3.5/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)


nan

In [106]:
vals2.max()

/Users/momo/.pyenv/versions/3.5.4/lib/python3.5/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)


nan

In [107]:
np.nansum(vals2)

8.0

In [108]:
np.nanmin(vals2)

1.0

In [109]:
np.nanmax(vals2)

4.0

Pandas中NaN与None的差异

In [111]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [113]:
x = pd.Series(range(2), dtype=int)

In [114]:
x

0    0
1    1
dtype: int64

In [115]:
x[0] = None

In [116]:
x

0    NaN
1    1.0
dtype: float64

In [117]:
x = pd.Series([1, 2, None], dtype=bool)

In [118]:
x

0     True
1     True
2    False
dtype: bool

发现缺失值

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.Series([1, np.nan, 'hello', None])

In [4]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [5]:
data[data.notnull()]

0        1
2    hello
dtype: object

剔除缺失值

In [7]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [8]:
data.dropna()

0        1
2    hello
dtype: object

In [9]:
df = pd.DataFrame([[1, np.nan, 2], 
                  [2, 3, 5], 
                  [np.nan, 4, 6]])

In [10]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [11]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [12]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [13]:
df[3] = np.nan

In [14]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [15]:
df.dropna(axis=1, how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [16]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [17]:
df.dropna(axis=0, thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

填充缺失值

In [18]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))

In [19]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [20]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [21]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [22]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [23]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [24]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

## 层级索引

In [11]:
import pandas as pd
import numpy as np

笨办法

In [12]:
index = [('a', 2000), ('a', 2010), ('b', 2000), ('b', 2010), ('c', 2000), ('c', 2010)]

In [13]:
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [14]:
pop = pd.Series(populations, index=index)

In [15]:
pop

(a, 2000)    33871648
(a, 2010)    37253956
(b, 2000)    18976457
(b, 2010)    19378102
(c, 2000)    20851820
(c, 2010)    25145561
dtype: int64

In [16]:
pop[('a', 2000): ('c', 2000)]

(a, 2000)    33871648
(a, 2010)    37253956
(b, 2000)    18976457
(b, 2010)    19378102
(c, 2000)    20851820
dtype: int64

In [17]:
pop[[i for i in pop.index if i[1] == 2010]]

(a, 2010)    37253956
(b, 2010)    19378102
(c, 2010)    25145561
dtype: int64

好方法：Pandas多级索引

In [18]:
index = pd.MultiIndex.from_tuples(index)

In [19]:
index

MultiIndex(levels=[['a', 'b', 'c'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [20]:
pop

(a, 2000)    33871648
(a, 2010)    37253956
(b, 2000)    18976457
(b, 2010)    19378102
(c, 2000)    20851820
(c, 2010)    25145561
dtype: int64

In [21]:
pop = pop.reindex(index)

In [22]:
pop

a  2000    33871648
   2010    37253956
b  2000    18976457
   2010    19378102
c  2000    20851820
   2010    25145561
dtype: int64

In [23]:
pop[:, 2010]

a    37253956
b    19378102
c    25145561
dtype: int64

高纬数据的多级索引

In [24]:
pop_df = pop.unstack()

In [25]:
pop_df

2000      2010
a  33871648  37253956
b  18976457  19378102
c  20851820  25145561

In [26]:
pop_df

2000      2010
a  33871648  37253956
b  18976457  19378102
c  20851820  25145561

In [27]:
pop_df.stack()

a  2000    33871648
   2010    37253956
b  2000    18976457
   2010    19378102
c  2000    20851820
   2010    25145561
dtype: int64

In [28]:
pop_df = pd.DataFrame({'total': pop, 
                      'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014]})

In [29]:
pop_df

total  under18
a 2000  33871648  9267089
  2010  37253956  9284094
b 2000  18976457  4687374
  2010  19378102  4318033
c 2000  20851820  5906301
  2010  25145561  6879014

In [30]:
f_u18 = pop_df['under18'] / pop_df['total']

In [31]:
f_u18

a  2000    0.273594
   2010    0.249211
b  2000    0.247010
   2010    0.222831
c  2000    0.283251
   2010    0.273568
dtype: float64

In [32]:
f_u18.unstack()

2000      2010
a  0.273594  0.249211
b  0.247010  0.222831
c  0.283251  0.273568

多级索引的创建方法

In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.DataFrame(np.random.rand(4, 2), index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]], columns=['data1', 'data2'])

In [35]:
df

data1     data2
a 1  0.283150  0.412448
  2  0.381486  0.149304
b 1  0.097793  0.018226
  2  0.671039  0.073066

In [36]:
data = {('a', 2000): 123123, 
       ('a', 2010): 1231112, 
       ('b', 2000): 43424234, 
       ('b', 2010): 32312312, 
       ('c', 2000): 4123123123, 
       ('c', 2010): 5342434}

In [37]:
pd.Series(data)

a  2000        123123
   2010       1231112
b  2000      43424234
   2010      32312312
c  2000    4123123123
   2010       5342434
dtype: int64

显式地创建多级索引

In [38]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [39]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [40]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [41]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]], labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [42]:
pop

a  2000    33871648
   2010    37253956
b  2000    18976457
   2010    19378102
c  2000    20851820
   2010    25145561
dtype: int64

In [43]:
pop.index

MultiIndex(levels=[['a', 'b', 'c'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [44]:
pop.index.names=['state', 'year']

In [45]:
pop

state  year
a      2000    33871648
       2010    37253956
b      2000    18976457
       2010    19378102
c      2000    20851820
       2010    25145561
dtype: int64

多级列索引

In [46]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], names=['year', 'visit'])

In [47]:
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names=['subject', 'type'])

In [48]:
data = np.round(np.random.randn(4, 6), 1)

In [49]:
data

array([[-2. , -0.1, -0.5, -1.5, -0.3,  0. ],
       [ 0.2, -0.2, -1.4,  1.7, -1.2, -0. ],
       [ 0.3,  0.7, -1. , -0.5,  0.7,  0.1],
       [ 1.1, -0.4,  1.5, -2.4, -0.7,  0.3]])

In [50]:
data[:, ::2] *= 10

In [51]:
data

array([[-20. ,  -0.1,  -5. ,  -1.5,  -3. ,   0. ],
       [  2. ,  -0.2, -14. ,   1.7, -12. ,  -0. ],
       [  3. ,   0.7, -10. ,  -0.5,   7. ,   0.1],
       [ 11. ,  -0.4,  15. ,  -2.4,  -7. ,   0.3]])

In [52]:
data += 37

In [53]:
data

array([[17. , 36.9, 32. , 35.5, 34. , 37. ],
       [39. , 36.8, 23. , 38.7, 25. , 37. ],
       [40. , 37.7, 27. , 36.5, 44. , 37.1],
       [48. , 36.6, 52. , 34.6, 30. , 37.3]])

In [54]:
health_data = pd.DataFrame(data, index=index, columns=columns)

In [55]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      17.0  36.9  32.0  35.5  34.0  37.0
     2      39.0  36.8  23.0  38.7  25.0  37.0
2014 1      40.0  37.7  27.0  36.5  44.0  37.1
     2      48.0  36.6  52.0  34.6  30.0  37.3

In [56]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      32.0  35.5
     2      23.0  38.7
2014 1      27.0  36.5
     2      52.0  34.6

In [57]:
pop

state  year
a      2000    33871648
       2010    37253956
b      2000    18976457
       2010    19378102
c      2000    20851820
       2010    25145561
dtype: int64

In [58]:
pop['a', 2000]

33871648

In [59]:
pop['a'][2000]

33871648

In [60]:
pop['a']

year
2000    33871648
2010    37253956
dtype: int64

In [61]:
pop.loc['a': 'b']

state  year
a      2000    33871648
       2010    37253956
b      2000    18976457
       2010    19378102
dtype: int64

In [62]:
pop.loc['c': 'a']

Series([], dtype: int64)

In [63]:
pop[:, 2000]

state
a    33871648
b    18976457
c    20851820
dtype: int64

In [64]:
pop[pop > 22000000]

state  year
a      2000    33871648
       2010    37253956
c      2010    25145561
dtype: int64

In [65]:
pop[['a', 'c']]

state  year
a      2000    33871648
       2010    37253956
c      2000    20851820
       2010    25145561
dtype: int64

In [66]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      17.0  36.9  32.0  35.5  34.0  37.0
     2      39.0  36.8  23.0  38.7  25.0  37.0
2014 1      40.0  37.7  27.0  36.5  44.0  37.1
     2      48.0  36.6  52.0  34.6  30.0  37.3

In [67]:
health_data['Guido', 'HR']

year  visit
2013  1        32.0
      2        23.0
2014  1        27.0
      2        52.0
Name: (Guido, HR), dtype: float64

In [68]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      17.0  36.9
     2      39.0  36.8

In [70]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        17.0
      2        39.0
2014  1        40.0
      2        48.0
Name: (Bob, HR), dtype: float64

In [71]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (<ipython-input-71-fb34fa30ac09>, line 1)

In [72]:
idx = pd.IndexSlice

In [73]:
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      17.0  32.0  34.0
2014 1      40.0  27.0  44.0

In [74]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      17.0  36.9  32.0  35.5  34.0  37.0
     2      39.0  36.8  23.0  38.7  25.0  37.0
2014 1      40.0  37.7  27.0  36.5  44.0  37.1
     2      48.0  36.6  52.0  34.6  30.0  37.3

有序索引和无序索引

错误的示范

In [75]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']

In [76]:
data

char  int
a     1      0.592662
      2      0.674041
c     1      0.859008
      2      0.316618
b     1      0.861399
      2      0.594797
dtype: float64

In [78]:
try:
    data['a', 'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'KeyError'>
('a', 'b')


In [79]:
data = data.sort_index()

In [80]:
data

char  int
a     1      0.592662
      2      0.674041
b     1      0.861399
      2      0.594797
c     1      0.859008
      2      0.316618
dtype: float64

In [82]:
data['a': 'b']

char  int
a     1      0.592662
      2      0.674041
b     1      0.861399
      2      0.594797
dtype: float64

索引stack和unstack

In [84]:
pop

state  year
a      2000    33871648
       2010    37253956
b      2000    18976457
       2010    19378102
c      2000    20851820
       2010    25145561
dtype: int64

In [85]:
pop.unstack(level=0)

state         a         b         c
year                               
2000   33871648  18976457  20851820
2010   37253956  19378102  25145561

In [86]:
pop.unstack(level=1)

year       2000      2010
state                    
a      33871648  37253956
b      18976457  19378102
c      20851820  25145561

In [87]:
pop.unstack().stack()

state  year
a      2000    33871648
       2010    37253956
b      2000    18976457
       2010    19378102
c      2000    20851820
       2010    25145561
dtype: int64

索引的设置与重置

In [88]:
pop

state  year
a      2000    33871648
       2010    37253956
b      2000    18976457
       2010    19378102
c      2000    20851820
       2010    25145561
dtype: int64

In [89]:
pop_flat = pop.reset_index(name="population")

In [90]:
pop_flat

state  year  population
0     a  2000    33871648
1     a  2010    37253956
2     b  2000    18976457
3     b  2010    19378102
4     c  2000    20851820
5     c  2010    25145561

In [91]:
pop_flat.set_index(['state', 'year'])

population
state year            
a     2000    33871648
      2010    37253956
b     2000    18976457
      2010    19378102
c     2000    20851820
      2010    25145561

In [92]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      17.0  36.9  32.0  35.5  34.0  37.0
     2      39.0  36.8  23.0  38.7  25.0  37.0
2014 1      40.0  37.7  27.0  36.5  44.0  37.1
     2      48.0  36.6  52.0  34.6  30.0  37.3

In [93]:
data_mean = health_data.mean(level='year')

In [94]:
data_mean

subject   Bob        Guido          Sue      
type       HR   Temp    HR   Temp    HR  Temp
year                                         
2013     28.0  36.85  27.5  37.10  29.5  37.0
2014     44.0  37.15  39.5  35.55  37.0  37.2

In [95]:
data_mean.mean(axis=1, level='type')

type         HR       Temp
year                      
2013  28.333333  36.983333
2014  40.166667  36.633333

## 合并数据集：Concat与Append操作

In [2]:
import pandas as pd
import numpy as np

In [11]:
def make_df(cols, ind):
    """一个简单的DataFrame"""
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)

In [98]:
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [3]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

In [4]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = [[1, 2], 
    [3, 4]]

In [6]:
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [7]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index = [4, 5, 6])

In [8]:
ser1

1    A
2    B
3    C
dtype: object

In [9]:
ser2

4    D
5    E
6    F
dtype: object

In [10]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [12]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

In [13]:
df1

A   B
1  A1  B1
2  A2  B2

In [14]:
df2

A   B
3  A3  B3
4  A4  B4

In [15]:
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [16]:
df3 = make_df('AB', [0, 1])

In [17]:
df4 = make_df('AB', [2, 3])

In [18]:
df3

A   B
0  A0  B0
1  A1  B1

In [19]:
df4

A   B
2  A2  B2
3  A3  B3

In [21]:
pd.concat([df3, df4], axis=1)

A    B    A    B
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2  NaN  NaN   A2   B2
3  NaN  NaN   A3   B3

索引重复

In [23]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

In [24]:
x

A   B
0  A0  B0
1  A1  B1

In [25]:
y

A   B
2  A2  B2
3  A3  B3

In [26]:
y.index = x.index

In [27]:
x

A   B
0  A0  B0
1  A1  B1

In [28]:
y

A   B
0  A2  B2
1  A3  B3

In [29]:
pd.concat([x, y])

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [30]:
y.index

Int64Index([0, 1], dtype='int64')

In [31]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError: ", e)

ValueError:  Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [32]:
x

A   B
0  A0  B0
1  A1  B1

In [33]:
y

A   B
0  A2  B2
1  A3  B3

In [36]:
pd.concat([x, y], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [37]:
pd.concat([x, y], keys=['x', 'y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [38]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])

In [39]:
df5

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [40]:
df6

B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [43]:
pd.concat([df5, df6], sort=False, join='outer')

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [44]:
pd.concat([df5, df6], sort=False, join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [45]:
pd.concat([df5, df6], join_axes=[df5.columns])

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [46]:
df1

A   B
1  A1  B1
2  A2  B2

In [47]:
df2

A   B
3  A3  B3
4  A4  B4

In [48]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

## 合并数据集：合并与连接

一对一连接

In [2]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'], 
                   'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'], 
                   'hire_date': ['2004', '2008', '2012', '2014']})

In [3]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [4]:
df2

employee hire_date
0     Lisa      2004
1      Bob      2008
2     Jake      2012
3      Sue      2014

In [5]:
df3 = pd.merge(df1, df2)

In [6]:
df3

employee        group hire_date
0      Bob   Accounting      2008
1     Jake  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014

多对一连接

In [7]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'], 
                   'supervisor': ['Carly', 'Guido', 'Steve']})

In [8]:
df3

employee        group hire_date
0      Bob   Accounting      2008
1     Jake  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014

In [9]:
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [10]:
pd.merge(df3, df4)

employee        group hire_date supervisor
0      Bob   Accounting      2008      Carly
1     Jake  Engineering      2012      Guido
2     Lisa  Engineering      2004      Guido
3      Sue           HR      2014      Steve

多对多连接

In [12]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting', 'Engineering', 'Engineering', 'HR', 'HR'], 
                   'skills': ['math', 'spreadsheets', 'coding', 'linux', 'spreadsheets', 'organization']})

In [13]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [14]:
df5

group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [15]:
pd.merge(df1, df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

参数on的用法

In [16]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [17]:
df2

employee hire_date
0     Lisa      2004
1      Bob      2008
2     Jake      2012
3      Sue      2014

In [18]:
pd.merge(df1, df2, on='employee')

employee        group hire_date
0      Bob   Accounting      2008
1     Jake  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014

left_on与right_on参数

In [19]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 
                   'salary': [70000, 80000, 120000, 90000]})

In [20]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [21]:
df3

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [22]:
pd.merge(df1, df3, left_on='employee', right_on="name")

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [23]:
pd.merge(df1, df3, left_on='employee', right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

left_index与right_index

In [24]:
df1a = df1.set_index('employee')
df2a = df2.set_index("employee")

In [25]:
df1a

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

In [26]:
df2a

hire_date
employee          
Lisa          2004
Bob           2008
Jake          2012
Sue           2014

In [27]:
pd.merge(df1a, df2a, left_index=True, right_index=True)

group hire_date
employee                       
Bob        Accounting      2008
Jake      Engineering      2012
Lisa      Engineering      2004
Sue                HR      2014

In [28]:
df1a.join(df2a)

group hire_date
employee                       
Bob        Accounting      2008
Jake      Engineering      2012
Lisa      Engineering      2004
Sue                HR      2014

In [29]:
df1a

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

In [30]:
df3

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [31]:
pd.merge(df1a, df3, left_index=True, right_on='name')

group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

设置数据连接的集合操作规则

In [32]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'], 
                   'food': ['fish', 'beans', 'bread']}, 
                  columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'], 
                   'drink': ['wine', 'beer']}, 
                  columns=['name', 'drink'])

In [33]:
df6

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [34]:
df7

name drink
0    Mary  wine
1  Joseph  beer

In [35]:
pd.merge(df6, df7)

name   food drink
0  Mary  bread  wine

merge默认的是内连接

In [36]:
df6

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [37]:
df7

name drink
0    Mary  wine
1  Joseph  beer

In [38]:
pd.merge(df6, df7, how='inner')

name   food drink
0  Mary  bread  wine

除此之外还有outer, left, right

In [39]:
pd.merge(df6, df7, how='outer')

name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [40]:
pd.merge(df6, df7, how='left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [41]:
pd.merge(df6, df7, how='right')

name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

重复列名：suffixes参数

In [42]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 
                   'rank': [1, 2, 3, 4]})

In [44]:
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'], 
                   'rank': [3, 1, 4, 2]})

In [45]:
df8

name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

In [46]:
df9

name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

In [47]:
pd.merge(df8, df9, on='name')

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

自定义后缀名

In [48]:
pd.merge(df8, df9, on="name", suffixes=["_左", "_右"])

name  rank_左  rank_右
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

案例：美国各州的统计数据

In [1]:
path1 = "F:/JupyterWorkspace/BookStudy/book1_data/"

In [3]:
pop = pd.read_csv(path1 + "state-population.csv")

In [4]:
areas = pd.read_csv(path1 + "state-areas.csv")

In [5]:
abbrevs = pd.read_csv(path1 + "state-abbrevs.csv")

In [6]:
pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [7]:
areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [8]:
abbrevs.head()

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [9]:
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation')

In [11]:
merged = merged.drop('abbreviation', axis=1)

In [12]:
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [14]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [15]:
merged[merged['population'].isnull()].head()

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [16]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [17]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'

In [18]:
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'

In [19]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [20]:
final = pd.merge(merged, areas, on='state', how='left')

In [21]:
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [22]:
final.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [23]:
final['state'][final['area (sq. mi)'].isnull()].unique()

array(['United States'], dtype=object)

In [24]:
final.dropna(inplace=True)

In [25]:
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [26]:
data2010 = final.query("year == 2010 & ages == 'total'")

In [27]:
data2010.head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [28]:
data2010.set_index('state', inplace=True)

In [31]:
data2010.head()

state/region   ages  year  population  area (sq. mi)
state                                                          
Alabama              AL  total  2010   4785570.0        52423.0
Alaska               AK  total  2010    713868.0       656425.0
Arizona              AZ  total  2010   6408790.0       114006.0
Arkansas             AR  total  2010   2922280.0        53182.0
California           CA  total  2010  37333601.0       163707.0

In [33]:
density = data2010['population'] / data2010['area (sq. mi)']

In [34]:
density.head()

state
Alabama        91.287603
Alaska          1.087509
Arizona        56.214497
Arkansas       54.948667
California    228.051342
dtype: float64

In [35]:
density.sort_values(ascending=False, inplace=True)

In [36]:
density.head()

state
District of Columbia    8898.897059
Puerto Rico             1058.665149
New Jersey              1009.253268
Rhode Island             681.339159
Connecticut              645.600649
dtype: float64

In [37]:
density.tail()

state
South Dakota    10.583512
North Dakota     9.537565
Montana          6.736171
Wyoming          5.768079
Alaska           1.087509
dtype: float64

## 累计与分组

### 行星数据

In [8]:
import seaborn as sns

In [9]:
planets = sns.load_dataset('planets')

In [10]:
planets.shape

(1035, 6)

In [41]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

### Pandas的简单累计功能

In [42]:
import numpy as np
import pandas as pd

In [43]:
rng = np.random.RandomState(42)

In [44]:
ser = pd.Series(rng.rand(5))

In [45]:
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [46]:
ser.sum()

2.811925491708157

In [47]:
ser.mean()

0.5623850983416314

In [48]:
df = pd.DataFrame({'A': rng.rand(5), 
                  'B': rng.rand(5)})

In [49]:
df

A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [50]:
df.mean()

A    0.477888
B    0.443420
dtype: float64

In [52]:
df.mean(axis=1)

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [53]:
df.mean(axis='columns')

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [55]:
planets.isnull().any()

method            False
number            False
orbital_period     True
mass               True
distance           True
year              False
dtype: bool

In [56]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

### GroupBy: 分割、应用和组合

In [27]:
import pandas as pd

In [28]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                  'data': range(6)}, columns=['key', 'data'])

In [29]:
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [30]:
df.groupby('key')

In [31]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [32]:
x = [1, 2, 3]
a =3
x.index(3)

2

In [33]:
planets.groupby('method')

In [34]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [35]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [36]:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)


In [37]:
planets.groupby('method')['year'].describe()

count         mean       std     min      25%  \
method                                                                         
Astrometry                       2.0  2011.500000  2.121320  2010.0  2010.75   
Eclipse Timing Variations        9.0  2010.000000  1.414214  2008.0  2009.00   
Imaging                         38.0  2009.131579  2.781901  2004.0  2008.00   
Microlensing                    23.0  2009.782609  2.859697  2004.0  2008.00   
Orbital Brightness Modulation    3.0  2011.666667  1.154701  2011.0  2011.00   
Pulsar Timing                    5.0  1998.400000  8.384510  1992.0  1992.00   
Pulsation Timing Variations      1.0  2007.000000       NaN  2007.0  2007.00   
Radial Velocity                553.0  2007.518987  4.249052  1989.0  2005.00   
Transit                        397.0  2011.236776  2.077867  2002.0  2010.00   
Transit Timing Variations        4.0  2012.500000  1.290994  2011.0  2011.75   

                                  50%      75%     max  
method                                                  
Astrometry                     2011.5  2012.25  2013.0  
Eclipse Timing Variations      2010.0  2011.00  2012.0  
Imaging                        2009.0  2011.00  2013.0  
Microlensing                   2010.0  2012.00  2013.0  
Orbital Brightness Modulation  2011.0  2012.00  2013.0  
Pulsar Timing                  1994.0  2003.00  2011.0  
Pulsation Timing Variations    2007.0  2007.00  2007.0  
Radial Velocity                2009.0  2011.00  2014.0  
Transit                        2012.0  2013.00  2014.0  
Transit Timing Variations      2012.5  2013.25  2014.0

In [38]:
planets.groupby('method')['year'].describe().unstack()

       method                       
count  Astrometry                          2.000000
       Eclipse Timing Variations           9.000000
       Imaging                            38.000000
       Microlensing                       23.000000
       Orbital Brightness Modulation       3.000000
       Pulsar Timing                       5.000000
       Pulsation Timing Variations         1.000000
       Radial Velocity                   553.000000
       Transit                           397.000000
       Transit Timing Variations           4.000000
mean   Astrometry                       2011.500000
       Eclipse Timing Variations        2010.000000
       Imaging                          2009.131579
       Microlensing                     2009.782609
       Orbital Brightness Modulation    2011.666667
       Pulsar Timing                    1998.400000
       Pulsation Timing Variations      2007.000000
       Radial Velocity                  2007.518987
       Transit             

In [39]:
import numpy as np

In [40]:
rng = np.random.RandomState(0)

In [41]:
rng.randint(0, 10, 6)

array([5, 0, 3, 3, 7, 9])

In [42]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                  'data1': range(6),
                  'data2': rng.randint(0, 10, 6)},
                  columns = ['key', 'data1', 'data2'])

In [43]:
df

key  data1  data2
0   A      0      3
1   B      1      5
2   C      2      2
3   A      3      4
4   B      4      7
5   C      5      6

In [46]:
df.groupby('key').aggregate(['min', np.median, max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    3.5   4
B       1    2.5   4     5    6.0   7
C       2    3.5   5     2    4.0   6

In [48]:
df.groupby('key').aggregate({'data1': 'min', 'data2': 'max'})

data1  data2
key              
A        0      4
B        1      7
C        2      6

In [53]:
def filter_func(x):
    return x['data2'].std() > 2

In [50]:
df

key  data1  data2
0   A      0      3
1   B      1      5
2   C      2      2
3   A      3      4
4   B      4      7
5   C      5      6

In [51]:
df.groupby('key').std()

data1     data2
key                   
A    2.12132  0.707107
B    2.12132  1.414214
C    2.12132  2.828427

In [54]:
df.groupby('key').filter(filter_func)

key  data1  data2
2   C      2      2
5   C      5      6

In [55]:
df.groupby('key').transform(lambda x: x - x.mean())

data1  data2
0   -1.5   -0.5
1   -1.5   -1.0
2   -1.5   -2.0
3    1.5    0.5
4    1.5    1.0
5    1.5    2.0

In [56]:
def norm_by_data2(x):
    # x是一个分组数据的DataFrame
    x['data1'] /= x['data2'].sum()
    return x

In [57]:
df

key  data1  data2
0   A      0      3
1   B      1      5
2   C      2      2
3   A      3      4
4   B      4      7
5   C      5      6

In [58]:
df.groupby('key').apply(norm_by_data2)

key     data1  data2
0   A  0.000000      3
1   B  0.083333      5
2   C  0.250000      2
3   A  0.428571      4
4   B  0.333333      7
5   C  0.625000      6

将列表、数组、Series或索引作为分组键

In [59]:
l = [0, 1, 0, 1, 2, 0]

In [60]:
df

key  data1  data2
0   A      0      3
1   B      1      5
2   C      2      2
3   A      3      4
4   B      4      7
5   C      5      6

In [61]:
df.groupby(l).sum()

data1  data2
0      7     11
1      4      9
2      4      7

In [64]:
df.groupby(l).max()

key  data1  data2
0   C      5      6
1   B      3      5
2   B      4      7

groupy按列表分组，可以理解为重新设置index为[0, 1, 0, 1, 2, 0]

In [65]:
df

key  data1  data2
0   A      0      3
1   B      1      5
2   C      2      2
3   A      3      4
4   B      4      7
5   C      5      6

In [66]:
df.groupby(df['key']).sum()

data1  data2
key              
A        3      7
B        5     12
C        7      8

用字典或Series将索引映射到分组名称。

In [67]:
df2 = df.set_index('key')

In [68]:
df2

data1  data2
key              
A        0      3
B        1      5
C        2      2
A        3      4
B        4      7
C        5      6

In [69]:
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant'}

In [71]:
df2.groupby(mapping).sum()

data1  data2
consonant     12     20
vowel          3      7

任意python函数

In [72]:
df2.groupby(str.lower).mean()

data1  data2
a    1.5    3.5
b    2.5    6.0
c    3.5    4.0

In [73]:
str

str

多个有效键构成的列表。

In [74]:
df2.groupby([str.lower, mapping]).mean()

data1  data2
a vowel        1.5    3.5
b consonant    2.5    6.0
c consonant    3.5    4.0

分组案例

In [76]:
decade = 10 * (planets['year'] // 10)

In [77]:
decade = decade.astype(str) + 's'

In [78]:
decade

0       2000s
1       2000s
2       2010s
3       2000s
4       2000s
5       2000s
6       2000s
7       1990s
8       2000s
9       2010s
10      2010s
11      2000s
12      2000s
13      1990s
14      2000s
15      2000s
16      1990s
17      1990s
18      2000s
19      2000s
20      2010s
21      2000s
22      2000s
23      2000s
24      2000s
25      1990s
26      2010s
27      2000s
28      2010s
29      2000s
        ...  
1005    2010s
1006    2010s
1007    2010s
1008    2010s
1009    2010s
1010    2010s
1011    2010s
1012    2010s
1013    2010s
1014    2010s
1015    2010s
1016    2010s
1017    2010s
1018    2010s
1019    2010s
1020    2010s
1021    2010s
1022    2010s
1023    2010s
1024    2010s
1025    2010s
1026    2010s
1027    2010s
1028    2010s
1029    2010s
1030    2000s
1031    2000s
1032    2000s
1033    2000s
1034    2000s
Name: year, Length: 1035, dtype: object

In [79]:
decade.name = 'decade'

In [80]:
decade

0       2000s
1       2000s
2       2010s
3       2000s
4       2000s
5       2000s
6       2000s
7       1990s
8       2000s
9       2010s
10      2010s
11      2000s
12      2000s
13      1990s
14      2000s
15      2000s
16      1990s
17      1990s
18      2000s
19      2000s
20      2010s
21      2000s
22      2000s
23      2000s
24      2000s
25      1990s
26      2010s
27      2000s
28      2010s
29      2000s
        ...  
1005    2010s
1006    2010s
1007    2010s
1008    2010s
1009    2010s
1010    2010s
1011    2010s
1012    2010s
1013    2010s
1014    2010s
1015    2010s
1016    2010s
1017    2010s
1018    2010s
1019    2010s
1020    2010s
1021    2010s
1022    2010s
1023    2010s
1024    2010s
1025    2010s
1026    2010s
1027    2010s
1028    2010s
1029    2010s
1030    2000s
1031    2000s
1032    2000s
1033    2000s
1034    2000s
Name: decade, Length: 1035, dtype: object

In [81]:
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

In [82]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

3.9完