In [1]:
from array import array

In [2]:
from random import random

In [3]:
floats = array('d', (random() for i in range(10 ** 7)))

In [4]:
floats[-1]

0.10782850673698374

In [7]:
fp = open('floats.bin', 'wb')

In [11]:
floats.tofile(fp)

In [12]:
fp.close()

In [14]:
from array import array

In [15]:
numbers = array('h', [-2, -1, 0, 1, 2])

In [16]:
memv = memoryview(numbers)

In [17]:
len(memv)

5

In [18]:
memv[0]

-2

In [19]:
memv_otc = memv.cast('B')

In [20]:
memv_otc.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [21]:
memv_otc[5] = 4

In [22]:
numbers

array('h', [-2, -1, 1024, 1, 2])

In [23]:
import numpy as np

In [26]:
a = np.arange(12)

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
type(a)

numpy.ndarray

In [29]:
a.shape

(12,)

In [30]:
a.shape = (3, 4)

In [31]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.shape = (3, 2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [33]:
a[2]

array([ 8,  9, 10, 11])

In [34]:
a[2, 1]

9

In [35]:
a[:, 1]

array([1, 5, 9])

In [36]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [37]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [40]:
import numpy as np

In [44]:
floats = np.loadtxt('a.txt')

In [45]:
floats

array([[ 333.,  123.],
       [1234.,   12.]])

In [46]:
from collections import deque

In [47]:
dq = deque(range(10), maxlen=10)

In [48]:
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
dq.rotate(3)

In [50]:
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [51]:
dq.rotate(-4)

In [52]:
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [53]:
dq.appendleft(-1)

In [54]:
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
dq.extend([11, 22, 33])

In [56]:
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [57]:
dq.extendleft([10, 20, 30, 40])

In [58]:
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

In [59]:
a, b, *c = 1, 2, 3, 4, 5

In [60]:
c

[3, 4, 5]

In [61]:
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19]

In [62]:
l

[28, 14, '28', 5, '9', '1', 0, 6, '23', 19]

In [63]:
sorted(l, key=int)

[0, '1', 5, 6, '9', 14, 19, '23', 28, '28']

In [64]:
sorted(l)

TypeError: '<' not supported between instances of 'str' and 'int'

In [65]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
