In [2]:
import numpy as np

In [3]:
np.ones(shape=(5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [4]:
x = np.random.normal(loc=15, scale=10, size=16)

In [5]:
x

array([19.29703827, 15.70784743, 10.0044237 ,  4.5807685 , -1.42094663,
       12.42536041, 12.08575673, 11.93456637, 29.51025953, 22.27008025,
       18.66937454, 28.2358969 , 22.78616128,  7.17171113, -1.49034222,
       21.78775605])

In [6]:
x.mean()

14.597232015763321

In [7]:
x.std()

9.137896922763357

In [8]:
x.var()

83.50116017104801

In [9]:
x

array([19.29703827, 15.70784743, 10.0044237 ,  4.5807685 , -1.42094663,
       12.42536041, 12.08575673, 11.93456637, 29.51025953, 22.27008025,
       18.66937454, 28.2358969 , 22.78616128,  7.17171113, -1.49034222,
       21.78775605])

In [10]:
x.ndim

1

In [11]:
x.dtype

dtype('float64')