In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
from pandas import Series, DataFrame

In [5]:
s = Series(np.random.randint(0, 150, size=10), index=list('abcdefhijk'), name='python')

In [6]:
s

a     49
b     17
c     65
d    100
e    126
f    103
h     58
i     74
j     95
k     18
Name: python, dtype: int32

In [8]:
s2 = Series({'A': 100, 'B': 137, 'C': 111})

In [9]:
s2

A    100
B    137
C    111
dtype: int64

In [10]:
type(s)

pandas.core.series.Series

In [11]:
s['d']

100

In [12]:
s[['d', 'e']]

d    100
e    126
Name: python, dtype: int32

In [13]:
s[2]

65

In [14]:
s

a     49
b     17
c     65
d    100
e    126
f    103
h     58
i     74
j     95
k     18
Name: python, dtype: int32

In [15]:
s.iloc[[0, 2]]

a    49
c    65
Name: python, dtype: int32

In [16]:
s.iloc[1:3]

b    17
c    65
Name: python, dtype: int32

In [17]:
s.loc['a']

49

In [18]:
s.shape

(10,)

In [19]:
s.size

10

In [20]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'h', 'i', 'j', 'k'], dtype='object')

In [21]:
s.values

array([ 49,  17,  65, 100, 126, 103,  58,  74,  95,  18])

In [22]:
 s.head()

a     49
b     17
c     65
d    100
e    126
Name: python, dtype: int32

In [23]:
s.tail()

f    103
h     58
i     74
j     95
k     18
Name: python, dtype: int32

In [25]:
s[['d', 'j']] = np.NaN

In [26]:
s

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [28]:
s.isnull()

a    False
b    False
c    False
d     True
e    False
f    False
h    False
i    False
j     True
k    False
Name: python, dtype: bool

In [29]:
cond = s.isnull()
s[cond]

d   NaN
j   NaN
Name: python, dtype: float64

In [31]:
cond = s.notnull()
s[cond]

a     49.0
b     17.0
c     65.0
e    126.0
f    103.0
h     58.0
i     74.0
k     18.0
Name: python, dtype: float64

In [32]:
s2

A    100
B    137
C    111
dtype: int64

In [33]:
s2.name

In [34]:
s2.name = 'Math'

In [35]:
s2

A    100
B    137
C    111
Name: Math, dtype: int64

In [36]:
s

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [37]:
s + 10

a     59.0
b     27.0
c     75.0
d      NaN
e    136.0
f    113.0
h     68.0
i     84.0
j      NaN
k     28.0
Name: python, dtype: float64

In [41]:
s3 = s.add(10, fill_value=0)

In [42]:
s3

a     59.0
b     27.0
c     75.0
d     10.0
e    136.0
f    113.0
h     68.0
i     84.0
j     10.0
k     28.0
Name: python, dtype: float64

In [44]:
s3.astype(np.uint8)

a     59
b     27
c     75
d     10
e    136
f    113
h     68
i     84
j     10
k     28
Name: python, dtype: uint8

In [45]:
s.mean()

63.75

In [46]:
s.median()

61.5

In [47]:
s.max()

126.0

In [48]:
s.std()

37.89364816731917

In [50]:
s.pow(2, fill_value=2)

a     2401.0
b      289.0
c     4225.0
d        4.0
e    15876.0
f    10609.0
h     3364.0
i     5476.0
j        4.0
k      324.0
Name: python, dtype: float64

In [51]:
s.value_counts()

18.0     1
74.0     1
58.0     1
103.0    1
126.0    1
65.0     1
17.0     1
49.0     1
Name: python, dtype: int64

In [52]:
s.T

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [53]:
s

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [54]:
df = DataFrame(data={'Python': np.random.randint(0, 150, size=5), 
                     'Math': np.random.randint(0, 150, size=5),
                    'English': np.random.randint(0, 150, size=5),
                    }, index=list('ABCDE'))

In [55]:
df

Python  Math  English
A     149   107       82
B      46   100       26
C      63   112       11
D     141    55       95
E      88     2      133

In [56]:
df2 = DataFrame(data=np.random.randint(0, 150, size=(10, 4)), index=list('ABCDEFHIJK'), columns=['Python', 'Math', 'English', 'Physic'])

In [57]:
df2

Python  Math  English  Physic
A      58    21       60      52
B     124    74       61      68
C     143    48      134      56
D     140    80      130      84
E      93   118      131       2
F      38    84       77      21
H     106     8       29      54
I      99    75      121      13
J      55   105       71      69
K     104    42      130      72

In [58]:
df2.to_clipboard()

In [60]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

In [61]:
datasets = load_iris()

In [63]:
X, y, y_names, feature_names = datasets['data'], datasets['target'], datasets['target_names'], datasets['feature_names']

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
clf = RandomForestClassifier()

In [74]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [79]:
y_pred = clf.predict(X_test)

In [77]:
clf.predict_proba(X_test)

array([[0.  , 1.  , 0.  ],
       [0.97, 0.03, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.84, 0.16],
       [0.99, 0.01, 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.05, 0.95],
       [0.  , 0.87, 0.13],
       [0.  , 1.  , 0.  ],
       [0.  , 0.06, 0.94],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.97, 0.03],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.09, 0.91],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99],
       [0.  , 0.01, 0.99],
       [0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [78]:
from sklearn.metrics import classification_report

In [83]:
output_dict = classification_report(y_test, y_pred, target_names=y_names, output_dict=True)

In [84]:
pd.DataFrame(output_dict)

setosa  versicolor  virginica  accuracy  macro avg  weighted avg
precision     1.0         1.0        1.0       1.0        1.0           1.0
recall        1.0         1.0        1.0       1.0        1.0           1.0
f1-score      1.0         1.0        1.0       1.0        1.0           1.0
support      10.0         9.0       11.0       1.0       30.0          30.0

In [85]:
df.values

array([[149, 107,  82],
       [ 46, 100,  26],
       [ 63, 112,  11],
       [141,  55,  95],
       [ 88,   2, 133]])

In [86]:
df.columns

Index(['Python', 'Math', 'English'], dtype='object')

In [87]:
df.shape

(5, 3)

In [88]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [89]:
df.dtypes

Python     int32
Math       int32
English    int32
dtype: object

In [90]:
df2

Python  Math  English  Physic
A      58    21       60      52
B     124    74       61      68
C     143    48      134      56
D     140    80      130      84
E      93   118      131       2
F      38    84       77      21
H     106     8       29      54
I      99    75      121      13
J      55   105       71      69
K     104    42      130      72

In [92]:
df2.Python

A     58
B    124
C    143
D    140
E     93
F     38
H    106
I     99
J     55
K    104
Name: Python, dtype: int32

In [93]:
df2[['Math', 'English']]

Math  English
A    21       60
B    74       61
C    48      134
D    80      130
E   118      131
F    84       77
H     8       29
I    75      121
J   105       71
K    42      130

In [94]:
df2.loc['A']

Python     58
Math       21
English    60
Physic     52
Name: A, dtype: int32

In [95]:
df2.loc[['A', 'C']]

Python  Math  English  Physic
A      58    21       60      52
C     143    48      134      56

In [96]:
df2.iloc[[3, 5]]

Python  Math  English  Physic
D     140    80      130      84
F      38    84       77      21

In [98]:
pd.__version__

'1.1.0'

In [99]:
df2.any()

Python     True
Math       True
English    True
Physic     True
dtype: bool

In [100]:
df2.all()

Python     True
Math       True
English    True
Physic     True
dtype: bool

In [101]:
df2.var()

Python     1288.888889
Math       1241.833333
English    1508.488889
Physic      765.211111
dtype: float64

In [102]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, A to K
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Python   10 non-null     int32
 1   Math     10 non-null     int32
 2   English  10 non-null     int32
 3   Physic   10 non-null     int32
dtypes: int32(4)
memory usage: 560.0+ bytes


In [104]:
df2.describe()

Python        Math    English     Physic
count   10.000000   10.000000   10.00000  10.000000
mean    96.000000   65.500000   94.40000  49.100000
std     35.901099   35.239656   38.83927  27.662449
min     38.000000    8.000000   29.00000   2.000000
25%     66.750000   43.500000   63.50000  28.750000
50%    101.500000   74.500000   99.00000  55.000000
75%    119.500000   83.000000  130.00000  68.750000
max    143.000000  118.000000  134.00000  84.000000

In [105]:
df1 = DataFrame(np.random.randint(0, 150, size=(5, 3)), index=list('ABCDE'), columns=['Python', 'Math', 'English'])

In [106]:
df1

Python  Math  English
A     135    66       24
B     124    62      146
C      21   111       21
D      60    87       38
E      44    24      146

In [107]:
df2 = DataFrame(np.random.randint(0, 150, size=(6,3)), index=list('ABCDEF'), columns=['Python', 'Math', 'English'])

In [108]:
df1 + df2

Python   Math  English
A   219.0  178.0     72.0
B   175.0  160.0    272.0
C   124.0  188.0     26.0
D   192.0  175.0    103.0
E    45.0  116.0    248.0
F     NaN    NaN      NaN

In [109]:
df2

Python  Math  English
A      84   112       48
B      51    98      126
C     103    77        5
D     132    88       65
E       1    92      102
F      88    34       30

In [112]:
df3 = df1.add(df2, fill_value=0)

In [113]:
df3

Python   Math  English
A   219.0  178.0     72.0
B   175.0  160.0    272.0
C   124.0  188.0     26.0
D   192.0  175.0    103.0
E    45.0  116.0    248.0
F    88.0   34.0     30.0

In [115]:
df3.loc['A': 'E'] = df3.loc['A': 'E'] / 2

In [116]:
df3

Python  Math  English
A   109.5  89.0     36.0
B    87.5  80.0    136.0
C    62.0  94.0     13.0
D    96.0  87.5     51.5
E    22.5  58.0    124.0
F    88.0  34.0     30.0

In [117]:
df1

Python  Math  English
A     135    66       24
B     124    62      146
C      21   111       21
D      60    87       38
E      44    24      146

In [118]:
s1 = df1.loc['A']

In [119]:
s1

Python     135
Math        66
English     24
Name: A, dtype: int32

In [120]:
df1.add(s1)

Python  Math  English
A     270   132       48
B     259   128      170
C     156   177       45
D     195   153       62
E     179    90      170

In [122]:
df1.add(s1, axis=0)

Python  Math  English
A           NaN   NaN      NaN
B           NaN   NaN      NaN
C           NaN   NaN      NaN
D           NaN   NaN      NaN
E           NaN   NaN      NaN
English     NaN   NaN      NaN
Math        NaN   NaN      NaN
Python      NaN   NaN      NaN

In [123]:
df1.add(s1)

Python  Math  English
A     270   132       48
B     259   128      170
C     156   177       45
D     195   153       62
E     179    90      170

In [124]:
df1.add(s1, axis=1)

Python  Math  English
A     270   132       48
B     259   128      170
C     156   177       45
D     195   153       62
E     179    90      170

In [125]:
s2 = df1.Python

In [126]:
s2

A    135
B    124
C     21
D     60
E     44
Name: Python, dtype: int32

In [127]:
df1.add(s2)

A   B   C   D   E  English  Math  Python
A NaN NaN NaN NaN NaN      NaN   NaN     NaN
B NaN NaN NaN NaN NaN      NaN   NaN     NaN
C NaN NaN NaN NaN NaN      NaN   NaN     NaN
D NaN NaN NaN NaN NaN      NaN   NaN     NaN
E NaN NaN NaN NaN NaN      NaN   NaN     NaN

In [128]:
df1.add(s2, axis=0)

Python  Math  English
A     270   201      159
B     248   186      270
C      42   132       42
D     120   147       98
E      88    68      190

In [129]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [131]:
df = DataFrame(np.random.randint(0, 150, size=(150, 3)), columns=['Python', 'Math', 'English"'])

In [132]:
df

Python  Math  English"
0        81   133       129
1        42    56       138
2       140   139        33
3        39   128       115
4       135    12        44
..      ...   ...       ...
145      14    73        37
146      53    67       129
147     130    25       119
148     143   108        35
149      49   134        53

[150 rows x 3 columns]

In [133]:
for i in range(15):
    index = np.random.randint(0, 150, size=1)[0]
    column = np.random.randint(0, 3, size=1)[0]
    df.iloc[index, column] = None

In [134]:
df

Python   Math  English"
0      81.0  133.0     129.0
1      42.0   56.0     138.0
2     140.0  139.0      33.0
3      39.0  128.0     115.0
4     135.0   12.0      44.0
..      ...    ...       ...
145    14.0   73.0      37.0
146     NaN   67.0     129.0
147   130.0   25.0     119.0
148   143.0  108.0      35.0
149    49.0  134.0      53.0

[150 rows x 3 columns]

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Python    143 non-null    float64
 1   Math      146 non-null    float64
 2   English"  146 non-null    float64
dtypes: float64(3)
memory usage: 3.6 KB


In [137]:
df.describe()

Python        Math    English"
count  143.000000  146.000000  146.000000
mean    74.377622   72.904110   77.136986
std     47.860685   44.005694   42.232792
min      0.000000    0.000000    0.000000
25%     29.000000   34.500000   38.750000
50%     74.000000   73.500000   80.000000
75%    121.500000  113.500000  115.750000
max    149.000000  147.000000  147.000000