In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
from pandas import Series, DataFrame

In [5]:
s = Series(np.random.randint(0, 150, size=10), index=list('abcdefhijk'), name='python')

In [6]:
s

a     49
b     17
c     65
d    100
e    126
f    103
h     58
i     74
j     95
k     18
Name: python, dtype: int32

In [8]:
s2 = Series({'A': 100, 'B': 137, 'C': 111})

In [9]:
s2

A    100
B    137
C    111
dtype: int64

In [10]:
type(s)

pandas.core.series.Series

In [11]:
s['d']

100

In [12]:
s[['d', 'e']]

d    100
e    126
Name: python, dtype: int32

In [13]:
s[2]

65

In [14]:
s

a     49
b     17
c     65
d    100
e    126
f    103
h     58
i     74
j     95
k     18
Name: python, dtype: int32

In [15]:
s.iloc[[0, 2]]

a    49
c    65
Name: python, dtype: int32

In [16]:
s.iloc[1:3]

b    17
c    65
Name: python, dtype: int32

In [17]:
s.loc['a']

49

In [18]:
s.shape

(10,)

In [19]:
s.size

10

In [20]:
s.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'h', 'i', 'j', 'k'], dtype='object')

In [21]:
s.values

array([ 49,  17,  65, 100, 126, 103,  58,  74,  95,  18])

In [22]:
 s.head()

a     49
b     17
c     65
d    100
e    126
Name: python, dtype: int32

In [23]:
s.tail()

f    103
h     58
i     74
j     95
k     18
Name: python, dtype: int32

In [25]:
s[['d', 'j']] = np.NaN

In [26]:
s

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [28]:
s.isnull()

a    False
b    False
c    False
d     True
e    False
f    False
h    False
i    False
j     True
k    False
Name: python, dtype: bool

In [29]:
cond = s.isnull()
s[cond]

d   NaN
j   NaN
Name: python, dtype: float64

In [31]:
cond = s.notnull()
s[cond]

a     49.0
b     17.0
c     65.0
e    126.0
f    103.0
h     58.0
i     74.0
k     18.0
Name: python, dtype: float64

In [32]:
s2

A    100
B    137
C    111
dtype: int64

In [33]:
s2.name

In [34]:
s2.name = 'Math'

In [35]:
s2

A    100
B    137
C    111
Name: Math, dtype: int64

In [36]:
s

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [37]:
s + 10

a     59.0
b     27.0
c     75.0
d      NaN
e    136.0
f    113.0
h     68.0
i     84.0
j      NaN
k     28.0
Name: python, dtype: float64

In [41]:
s3 = s.add(10, fill_value=0)

In [42]:
s3

a     59.0
b     27.0
c     75.0
d     10.0
e    136.0
f    113.0
h     68.0
i     84.0
j     10.0
k     28.0
Name: python, dtype: float64

In [44]:
s3.astype(np.uint8)

a     59
b     27
c     75
d     10
e    136
f    113
h     68
i     84
j     10
k     28
Name: python, dtype: uint8

In [45]:
s.mean()

63.75

In [46]:
s.median()

61.5

In [47]:
s.max()

126.0

In [48]:
s.std()

37.89364816731917

In [50]:
s.pow(2, fill_value=2)

a     2401.0
b      289.0
c     4225.0
d        4.0
e    15876.0
f    10609.0
h     3364.0
i     5476.0
j        4.0
k      324.0
Name: python, dtype: float64

In [51]:
s.value_counts()

18.0     1
74.0     1
58.0     1
103.0    1
126.0    1
65.0     1
17.0     1
49.0     1
Name: python, dtype: int64

In [52]:
s.T

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [53]:
s

a     49.0
b     17.0
c     65.0
d      NaN
e    126.0
f    103.0
h     58.0
i     74.0
j      NaN
k     18.0
Name: python, dtype: float64

In [54]:
df = DataFrame(data={'Python': np.random.randint(0, 150, size=5), 
                     'Math': np.random.randint(0, 150, size=5),
                    'English': np.random.randint(0, 150, size=5),
                    }, index=list('ABCDE'))

In [55]:
df

Python  Math  English
A     149   107       82
B      46   100       26
C      63   112       11
D     141    55       95
E      88     2      133

In [56]:
df2 = DataFrame(data=np.random.randint(0, 150, size=(10, 4)), index=list('ABCDEFHIJK'), columns=['Python', 'Math', 'English', 'Physic'])

In [57]:
df2

Python  Math  English  Physic
A      58    21       60      52
B     124    74       61      68
C     143    48      134      56
D     140    80      130      84
E      93   118      131       2
F      38    84       77      21
H     106     8       29      54
I      99    75      121      13
J      55   105       71      69
K     104    42      130      72

In [58]:
df2.to_clipboard()

In [60]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

In [61]:
datasets = load_iris()

In [63]:
X, y, y_names, feature_names = datasets['data'], datasets['target'], datasets['target_names'], datasets['feature_names']

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
clf = RandomForestClassifier()

In [74]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [79]:
y_pred = clf.predict(X_test)

In [77]:
clf.predict_proba(X_test)

array([[0.  , 1.  , 0.  ],
       [0.97, 0.03, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.84, 0.16],
       [0.99, 0.01, 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.05, 0.95],
       [0.  , 0.87, 0.13],
       [0.  , 1.  , 0.  ],
       [0.  , 0.06, 0.94],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.97, 0.03],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.09, 0.91],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99],
       [0.  , 0.01, 0.99],
       [0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [78]:
from sklearn.metrics import classification_report

In [83]:
output_dict = classification_report(y_test, y_pred, target_names=y_names, output_dict=True)

In [84]:
pd.DataFrame(output_dict)

setosa  versicolor  virginica  accuracy  macro avg  weighted avg
precision     1.0         1.0        1.0       1.0        1.0           1.0
recall        1.0         1.0        1.0       1.0        1.0           1.0
f1-score      1.0         1.0        1.0       1.0        1.0           1.0
support      10.0         9.0       11.0       1.0       30.0          30.0

In [85]:
df.values

array([[149, 107,  82],
       [ 46, 100,  26],
       [ 63, 112,  11],
       [141,  55,  95],
       [ 88,   2, 133]])

In [86]:
df.columns

Index(['Python', 'Math', 'English'], dtype='object')

In [87]:
df.shape

(5, 3)

In [88]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [89]:
df.dtypes

Python     int32
Math       int32
English    int32
dtype: object

In [90]:
df2

Python  Math  English  Physic
A      58    21       60      52
B     124    74       61      68
C     143    48      134      56
D     140    80      130      84
E      93   118      131       2
F      38    84       77      21
H     106     8       29      54
I      99    75      121      13
J      55   105       71      69
K     104    42      130      72

In [92]:
df2.Python

A     58
B    124
C    143
D    140
E     93
F     38
H    106
I     99
J     55
K    104
Name: Python, dtype: int32

In [93]:
df2[['Math', 'English']]

Math  English
A    21       60
B    74       61
C    48      134
D    80      130
E   118      131
F    84       77
H     8       29
I    75      121
J   105       71
K    42      130

In [94]:
df2.loc['A']

Python     58
Math       21
English    60
Physic     52
Name: A, dtype: int32

In [95]:
df2.loc[['A', 'C']]

Python  Math  English  Physic
A      58    21       60      52
C     143    48      134      56

In [96]:
df2.iloc[[3, 5]]

Python  Math  English  Physic
D     140    80      130      84
F      38    84       77      21

In [98]:
pd.__version__

'1.1.0'

In [99]:
df2.any()

Python     True
Math       True
English    True
Physic     True
dtype: bool

In [100]:
df2.all()

Python     True
Math       True
English    True
Physic     True
dtype: bool

In [101]:
df2.var()

Python     1288.888889
Math       1241.833333
English    1508.488889
Physic      765.211111
dtype: float64