Numpy测试

In [1]:
from numpy import *

In [2]:
random.rand(4, 4)

array([[0.14349926, 0.15698515, 0.1202379 , 0.06110009],
       [0.03158488, 0.7012314 , 0.15432514, 0.82541699],
       [0.48850187, 0.70109445, 0.84224174, 0.56228786],
       [0.29551611, 0.09024221, 0.76653691, 0.79259665]])

In [3]:
randMat = mat(random.rand(4,4))

In [4]:
randMat

matrix([[0.3296906 , 0.46431409, 0.02961592, 0.36966455],
        [0.9744083 , 0.78226819, 0.77198222, 0.7886608 ],
        [0.24165223, 0.94606265, 0.20925295, 0.22479255],
        [0.21909759, 0.07964611, 0.7227898 , 0.54977275]])

In [5]:
randMat.T

matrix([[0.3296906 , 0.9744083 , 0.24165223, 0.21909759],
        [0.46431409, 0.78226819, 0.94606265, 0.07964611],
        [0.02961592, 0.77198222, 0.20925295, 0.7227898 ],
        [0.36966455, 0.7886608 , 0.22479255, 0.54977275]])

In [6]:
randMat.I

matrix([[-0.97848987,  2.0250111 , -1.04084786, -1.82140534],
        [-0.08853294, -0.2848847 ,  1.3428322 , -0.08085849],
        [-2.6618204 ,  0.5527857 ,  0.7926704 ,  0.67270305],
        [ 3.90228999, -1.49249477, -0.82186355,  1.67211393]])

In [7]:
invRandMat = randMat.I

In [8]:
randMat * invRandMat

matrix([[ 1.00000000e+00,  1.32959163e-16, -2.04821534e-17,
          7.02683810e-17],
        [ 1.99190606e-16,  1.00000000e+00,  5.70946016e-17,
          4.32423756e-16],
        [-6.45562754e-18,  7.29536690e-17,  1.00000000e+00,
         -1.23984724e-17],
        [-1.41773170e-17,  8.28548756e-18, -8.51755709e-17,
          1.00000000e+00]])

In [9]:
myEye = randMat*invRandMat

In [10]:
myEye - eye(4)

matrix([[ 0.00000000e+00,  1.32959163e-16, -2.04821534e-17,
          7.02683810e-17],
        [ 1.99190606e-16,  2.22044605e-16,  5.70946016e-17,
          4.32423756e-16],
        [-6.45562754e-18,  7.29536690e-17,  0.00000000e+00,
         -1.23984724e-17],
        [-1.41773170e-17,  8.28548756e-18, -8.51755709e-17,
          0.00000000e+00]])

kNN实战

In [27]:
from numpy import *
import operator

In [26]:
def createDataSet():
    group = array([[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]])
    label = ['A', 'A', 'B', 'B']
    return group, label

In [22]:
group, labels = createDataSet()

In [23]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [24]:
labels

['A', 'A', 'B', 'B']

In [28]:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    
    # 距离计算
    diffMat = tile(inX, (dataSetSize, 1)) - dataSet
    sqDiffMat = diffMat ** 2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()
    
    # 选择距离最小的k个点
    classCount = {}
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1
    
    # 排序
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

In [29]:
classify0([0, 0], group, labels, 3)

'B'